buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
aptPkgs = ['...', 'bash']

[phases.build]
cmds = ['NODE_ENV=development node --max_old_space_size=4096 node_modules/.bin/react-scripts build']
